# Generated by Django 3.1 on 2021-07-02 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp_app', '0002_auto_20210702_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='name',
            field=models.CharField(default='alice and bob', max_length=20),
            preserve_default=False,
        ),
    ]
