# Generated by Django 3.1 on 2021-07-03 11:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('comp_app', '0004_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='submitted_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 3, 11, 24, 34, 794141, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
