# Generated by Django 3.1 on 2021-07-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp_app', '0005_solution_submitted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='verdict',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
