# Generated by Django 3.1 on 2021-07-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp_app', '0007_question_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='points',
            field=models.IntegerField(default=15),
            preserve_default=False,
        ),
    ]
